USE Empresa

CREATE TABLE Funcionarios (
CodigoFun INT NOT NULL PRIMARY KEY,
NomeFun NVARCHAR (70) NOT NULL,
Sobrenome NVARCHAR (50) NOT NULL,
Nascimento DATE NOT NULL,
CPF CHAR (11) NOT NULL,
RG CHAR (9) NOT NULL,
Endereco NVARCHAR (80) NOT NULL,
CEP CHAR (9) NOT NULL,
Cidade NVARCHAR (80) NOT NULL,
Telefone NVARCHAR (20) NOT NULL,
Cargo NVARCHAR (70) NOT NULL,
Salario DECIMAL (7,2) NOT NULL,
Codigo INT NOT NULL
CONSTRAINT CodigoDep FOREIGN KEY (Codigo)
REFERENCES Departamentos (CodigoDep)
);
GO