USE Locadora

CREATE TABLE CDs (
Codigo INT NOT NULL PRIMARY KEY,
NomeCd NVARCHAR NOT NULL,
DataCompra DATE NOT NULL,
ValorPago DECIMAL(5,2) NOT NULL,
LocalCompra NVARCHAR(60)NOT NULL,
Album BIT NOT NULL
);
GO