USE Entrega

CREATE TABLE Envio (
Cod_Envio INT NOT NULL PRIMARY KEY,
DataEnvio DATE NOT NULL,
NomeEnvio NVARCHAR(70) NOT NULL,
Frete DECIMAL(6,2) NOT NULL,
Cidade NVARCHAR(70) NOT NULL,
Regiao NVARCHAR(60) NOT NULL,
Pais NVARCHAR(40) NOT NULL,

);

GO
